### ISSUE TITLE
The Resource 'Microsoft.Network/virtualNetworks/XXXXXXX' under resource group 'XXXXXXXXX' was not found

### ISSUE THREAD

**Issue by pankajrohal** [Azure/RGCOPY#4]
Hi,

I am using RGCopy to copy resource from one RG to another RG. Can you please help with the below issue?

The deployment 'XXXXXXX.2022-10-26__17-19-45' failed with error(s). Showing 1 out of 1 error(s).
Status Message: The Resource 'Microsoft.Network/virtualNetworks/XXXXXXX' under resource group 'XXXXXXXXX' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix (Code:ResourceNotFound)

**Comment by martin-merdes** [comment]
Please send me the RGCOPY zip file

**Comment by pankajrohal** [comment]
Ok. I will arrange the same. 

I am using RGCopy from one RG to another in same region. I guess, it is possible to copy the RG in same region. Kindly clarify.

**Comment by pankajrohal** [comment]
Hi, I am not authorised to share the logs. Can you please tell me if it is possible to do Rgcopy from one RG to another within same region. I can see it is copying my resources with same IP and hostname in same region. I am not able to login to VM in target RG. Do I need to perform any post steps?

**Comment by martin-merdes** [comment]
Copying a resource group within the same region is the simplest configuration that you can use for RGCOPY. Yes, it is possible. However, RGCOPY does not support ALL resource types. I would like to help you and have a look at your configuration in the log files. However, I cannot help you without the RGCOPY ZIP file.
For logging on, you need a network connection and a local user. RGCOPY does not rename or re-join a VM to a domain controller, nor does it copy any required peered networks or VPNs.
Regards
Martin

**Comment by pankajrohal** [comment]
Thanks for your reply. I am copying the supported resource type which is SAP HANA DB. 

My Concerns are:
1. It is assigning the same host and IP to the target VM in target RG however Vnet is diff. Is it possible to still login with same IP in same region?
2. Can we stop to create another Vnet in target RG? I want to use the exiting Vnet. if possible. 
I will again reach out to the concerned person again if we can share the logs.

**Comment by martin-merdes** [comment]
- RGCOPY always performs a COPY, even of the vnet and a subnet. This copy just has the same name - it is not the same network
- RGCOPY does **not** support any SAP resource (e.g. HANA). RGCOPY supports Azure resources, see the RGCOPY documentation at [https://github.com/Azure/RGCOPY/blob/main/rgcopy-docu.md#supported-azure-resources](https://github.com/Azure/RGCOPY/blob/main/rgcopy-docu.md#supported-azure-resources)
- The Azure resource "Public IP Address" can be copied but its value (e.g. 10.20.30.40) cannot be copied because an IP address must be unique.

**Comment by pankajrohal** [comment]
Thanks for the clarification. Apologies for the multiple doubts due to my limited knowledge with Azure. 

I missed it while doing the research that SAP HANA deployed on Azure is not supported.

**Comment by martin-merdes** [comment]
That's not what exactly what I meant. "SAP HANA" is not a resource in Azure. Azure resources are VMs, disks, vnets etc. If these Azure resources build an SAP HANA system then you can copy it. However, only the Azure resources are copied. Nothing is changed on OS or SAP level like SAP profile, license, host name, IP address etc.
On the other hand you cannot generally say the SAP HANA is supported because the SAP HANA system might depend on Azure resources that are not supported by RGCOPY, e.g. a VPN or a domain controller outside the copied resource group

**Comment by pankajrohal** [comment]
Thanks for clarifying it. Let me explore it more. I will contact you in case of more doubts.

**Comment by pankajrohal** [comment]
Hi, can you please share your email id for sharing the logs?

**Comment by pankajrohal** [comment]
[rgcopy.Testing-2.2022-11-09__15-02-50.zip](https://github.com/Azure/RGCOPY/files/9969820/rgcopy.Testing-2.2022-11-09__15-02-50.zip)

**Comment by pankajrohal** [comment]
shared the logs via private repository.

**Comment by martin-merdes** [comment]
Hi Pankaj,

I had a look at your log files and figured out the following:

RGCOPY does not support network peering (only in one special case with AMS v1 - see the online documentation). RGCOPY did not support VNETs that were located in a different resource group (other RG than the source RG). Therefore, I implemented a workaround that also copies remote VNETs. 

However, your remote VNET contains network peering. This special case has not been coded in RGCOPY yet. Unfortunately, this cannot be quickly fixed with just a few lines of code. I will put this on my list for the next version of RGCOPY. Please do not expect a new version within the next few weeks.

Regards
Martin

**Comment by pankajrohal** [comment]
Therefore, I implemented a workaround that also copies remote VNETs.--> Can I try it again using the RGCopy? I mean is it available on Github after the workaround?

**Comment by martin-merdes** [comment]
The workaround is already implemented and on GitHub - BUT it does not support network peering for remote networks.
There is no RGCOPY fix for your specific configuration (network in a remote resource group and using network peering at the same time)

**Comment by martin-merdes** [comment]
I have released RGCOPY 0.9.44. This should solve the issue
